# Generated by Django 2.2.2 on 2019-06-18 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='address',
            field=models.CharField(default='Austin, TX', max_length=250),
        ),
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(default='Food', max_length=100),
        ),
        migrations.AddField(
            model_name='post',
            name='date',
            field=models.DateField(default='2020-01-01', verbose_name='Post Date'),
        ),
    ]
